### PR TITLE
fix(service-controller): Updates not working

### LINKED ISSUE #405: LoadBalancer Services not re-reconciling on changes to modulesets or traffic policy
When changing a moduleset, updates do not trigger re-reconciles of services. This is most likely caused by not fully implementing the watches:

https://github.com/ngrok/kubernetes-ingress-controller/blob/fc9f93ee2c09b275c6b48889a159d60d7c54670d/internal/controller/ingress/service_controller.go#L90

### PR DESCRIPTION
**Pull request by jonstacks**
Fixes #405 

## What

Fixes a bug where changing/adding annotations(ex: `k8s.ngrok.com/modules`) did not update the underlying TCP/TLS Edge spec. Also, the service controller was previously not watching for changes to ngrok modulesets or traffic policy CRs. This also fixes that.

## How
* fix bug that was overwriting the desired state with the existing state
* Add watches & indexers so when a moduleset or traffic policy changes, we trigger a reconcile of services that use the moduleset or traffic policy
* Also pulls in an update to the bitnami/common library chart. We probably want to disable to auto update mechanism in favor of just building helm deps initially, but that is out of scope for this.

## Breaking Changes
no

### CODE REVIEW

File: internal/controller/ingress/service_controller.go [hunk 1]
```diff
@@ -86,9 +92,19 @@ func (r *ServiceReconciler) SetupWithManager(mgr ctrl.Manager) error {
...
 			},
-		})
-		// TODO: Add watches for modulesets and traffic policies so we get updates
-
+		}).
+		// Watch modulesets for changes
+		Watches(
+			&ingressv1alpha1.NgrokModuleSet{},
+			handler.EnqueueRequestsFromMapFunc(r.findServicesForModuleSet),
+		).
```
Comment (alex-bezek) [inline internal/controller/ingress/service_controller.go:100]: Since the moduleset also can reference a secret, I assume we'd also want to trigger a reconcile when a secret is updated? This is the problem with the https edge https://github.com/ngrok/kubernetes-ingress-controller/issues/177 which I assume is applicable here as well? If so, should we also watch the secret here, or should we just solve this problem across multiple controllers at a later time?

File: internal/controller/ingress/service_controller.go [hunk 2]
```diff
@@ -108,6 +124,34 @@ func (r *ServiceReconciler) SetupWithManager(mgr ctrl.Manager) error {
 		}
 	}
 
+	// Index the services by the module set(s) they reference
+	err := mgr.GetFieldIndexer().IndexField(context.Background(), &corev1.Service{}, ModuleSetPath, func(obj client.Object) []string {
```
Comment (alex-bezek) [inline internal/controller/ingress/service_controller.go:128]: this is new to me, is this just a more efficient way than to get all the objects or something?

**Review by alex-bezek — APPROVED** [review]

File: internal/controller/ingress/service_controller.go (hunk 2 above)
Comment (jonstacks) [reply internal/controller/ingress/service_controller.go:128]: This indexes the services by the module sets the use. This allows us to efficiently answer the question: "which services need to be reconciled when a module set changes" and then trigger the reconciles for those services. For modulesets, of which you can have multiple in the annotation, this comment in the FieldIndexer is important:

https://github.com/kubernetes-sigs/controller-runtime/blob/6f1c3d819175d2c2f72865c6e544b0f78dc8c280/pkg/client/interfaces.go#L196-L202

File: internal/controller/ingress/service_controller.go (hunk 1 above)
Comment (jonstacks) [reply internal/controller/ingress/service_controller.go:100]: The secret watching needs to happen in the HTTPSEdge,TLSEdge, and TCPEdge controllers. We'll fix that in a future PR
